In [1]:
import tensorflow as tf
class One_Feature_Node:
    def __init__(self):
        self.w = tf.Variable([[0.1]]) ## 학습이 진행되면서 계속 변하는 값
        self.b = tf.Variable([[0.5]]) 
    
    def __call__(self, x):
        return self.get_output(x)

    def get_output(self, x):
        out = tf.matmul(x, self.w)
        out = tf.add(out, self.b)
        out = tf.math.sigmoid(out)
        
        return out

## single Input
x = tf.constant([[1.0]]) ## 수집된 데이터의 값은 변하지 않기때문에 상수로 지정함

##Run
one_feature_node = One_Feature_Node()
one_feature_node(x)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.6456563]], dtype=float32)>

In [10]:
import tensorflow as tf
class Two_Feature_Node:
    def __init__(self):
        self.w = tf.Variable([[0.1],[0.2]]) ## 학습이 진행되면서 계속 변하는 값
        self.b = tf.Variable([[0.5]]) 
    
    def __call__(self, x):
        return self.get_output(x)

    def get_output(self, x):
        print("shape of self.w : {}".format(self.w.shape))
        print("shape of x : {}".format(x.shape))
        out = tf.matmul(x, self.w)
        out = tf.add(out, self.b)
        out = tf.math.sigmoid(out)
        
        return out

## two feature Input
x = tf.constant([[1.0, 2.0]]) ## 수집된 데이터의 값은 변하지 않기때문에 상수로 지정함

##Run
two_feature_node = Two_Feature_Node()
f =two_feature_node(x)
print(f)

shape of self.w : (2, 1)
shape of x : (1, 2)
tf.Tensor([[0.7310586]], shape=(1, 1), dtype=float32)


In [24]:
class Node:
    def __init__(self):
        self.w = tf.Variable(tf.random.normal([2,1])) ## 초기 랜덤 variable을 줌
        self.b = tf.Variable(tf.random.normal([1,1]))
    
    def __call__(self, x):
        return self.preds(x)


    def preds(self, x):
        #forward backpropagation
        # print("shape of self.w : {}".format(self.w.shape))
        # print("shape of x : {}".format(x.shape))       
        # print("shape of self.b : {}".format(self.b.shape))     
        out = tf.matmul(x, self.w)
        out = tf.add(out, self.b)
        out = tf.nn.sigmoid(out)
        
        return out

    def loss(self, y_pred, y):
        # print("shape of  tf.square(y_pred -y) : {}".format(tf.square(y_pred -y).shape)) (4,1)
        return tf.reduce_mean(tf.square(y_pred -y))   # reduce_mean은 특정 차원을 제거하고 평균을 구한다.
    
    def train(self, inputs, outputs, learning_rate):
        epochs = range(10000)
        for i, epoch in enumerate(epochs):
            with tf.GradientTape() as t:
                current_loss = self.loss(self.preds(inputs), outputs)
                if i % 1000 == 0:
                    print(str(i)+" epoch, loss "+ str(current_loss.numpy()))
                # back propagation

                print("cur_loss : {}".format(current_loss))
                dW, db = t.gradient(current_loss, [self.w, self.b])
                print("dW : {},db : {}".format(dW, db))

                self.w.assign_sub(learning_rate* dW)
                self.b.assign_sub(learning_rate* db)



In [25]:
## And operation
inputs = tf.constant([[0.0,0.0],[0.0,1.0],[1.0,0.0],[1.0,1.0]])
outputs = tf.constant([[0.0],[0.0],[0.0],[1.0]])

node = Node()

# train
node.train(inputs,outputs,0.01)

# test
assert node([[0.0,0.0]]).numpy()[0][0] < 0.5
assert node([[0.0,1.0]]).numpy()[0][0] < 0.5
assert node([[1.0,0.0]]).numpy()[0][0] < 0.5
assert node([[1.0,1.0]]).numpy()[0][0] >= 0.5


0 epoch, loss 0.2920287
cur_loss : 0.2920286953449249
dW : [[ 0.00188846]
 [-0.04800152]],db : [[0.07109567]]
cur_loss : 0.2919551134109497
dW : [[ 0.00187165]
 [-0.04799821]],db : [[0.07105035]]
cur_loss : 0.29188159108161926
dW : [[ 0.00185482]
 [-0.0479949 ]],db : [[0.07100504]]
cur_loss : 0.2918080687522888
dW : [[ 0.00183798]
 [-0.04799161]],db : [[0.0709597]]
cur_loss : 0.2917346954345703
dW : [[ 0.00182115]
 [-0.04798832]],db : [[0.07091441]]
cur_loss : 0.2916613221168518
dW : [[ 0.00180428]
 [-0.04798505]],db : [[0.07086907]]
cur_loss : 0.2915881276130676
dW : [[ 0.00178742]
 [-0.04798177]],db : [[0.07082377]]
cur_loss : 0.29151493310928345
dW : [[ 0.00177053]
 [-0.04797851]],db : [[0.07077846]]
cur_loss : 0.29144173860549927
dW : [[ 0.00175364]
 [-0.04797526]],db : [[0.07073314]]
cur_loss : 0.2913687229156494
dW : [[ 0.00173675]
 [-0.04797201]],db : [[0.07068785]]
cur_loss : 0.29129570722579956
dW : [[ 0.00171984]
 [-0.04796878]],db : [[0.07064255]]
cur_loss : 0.29122281074523

KeyboardInterrupt: 

In [27]:
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
# random seed for always same results
tf.random.set_seed(678)

import numpy as np

In [28]:
X = np.array([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
y = np.array([0.,1.,1.,0.])

print(X.shape)
print(y.shape)

(4, 2)
(4,)


In [29]:
model = Sequential()
# first dense layer
model.add(Dense(units=2,activation='sigmoid',input_dim=2))
# second dense layer
model.add(Dense(units=1,activation='sigmoid'))

In [31]:
# loss function and optimization
model.compile(loss='binary_crossentropy',optimizer='sgd',metrics=['accuracy'])

In [32]:
# model summary
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________
None


In [33]:
# Train (takes about 3 minutes from Colab)
model.fit(X,y,epochs=50000,batch_size=4,verbose=0)

# Test
[0, 0], [0, 1] outputs are less than 0.5,  
[0, 1], [1, 0] outputs are greater than 0.5

In [34]:
print(model.predict(X,batch_size=4))

[[0.06190899]
 [0.94067526]
 [0.940909  ]
 [0.07283726]]


# Print Second Dense layer's weights and bias   
weights are -7.8013854, 7.392064, bias is-3.3388186

In [56]:
print("second layer weights: ",model.layers[1].get_weights()[0])
print("second layer bias: ",model.layers[1].get_weights()[1])

print(model.layers[0].get_weights()[0].shape)
print(model.layers[0].get_weights()[1].shape)
print(model.layers[1].get_weights()[0].shape)
print(model.layers[1].get_weights()[1].shape)


second layer weights:  [[-7.8013864]
 [ 7.392065 ]]
second layer bias:  [-3.338819]
(2, 2)
(2,)
(2, 1)
(1,)


# calculate yourself and verify same result with TF dense layers

In [36]:
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))

In [37]:
def get_output(x):
    layer0 = model.layers[0]
    # first dense layer, first node output
    layer0_weights, layer0_bias = layer0.get_weights()
    layer0_node0_weights = np.transpose(layer0_weights)[0]
    layer0_node0_bias = layer0_bias[0]
    layer0_node0_output = sigmoid( np.dot( x, layer0_node0_weights ) + layer0_node0_bias )
    # second dense layer, second node output
    layer0_node1_weights = np.transpose(layer0_weights)[1]
    layer0_node1_bias = layer0_bias[1]
    layer0_node1_output = sigmoid( np.dot( x, layer0_node1_weights ) + layer0_node1_bias )
    # second layer output
    layer1 = model.layers[1]
    layer1_weights, layer1_bias = layer1.get_weights()
    layer1_output = sigmoid( np.dot( [layer0_node0_output, layer0_node1_output], layer1_weights ) + layer1_bias )

    print(layer1_output)

In [39]:
get_output([0,0])

0.061909038110613504


In [40]:
get_output([0,1])

0.9406752195343842


In [ ]:
get_output([1,0])

In [ ]:
get_output([1,1])